In [2]:
import pandas as pd
import numpy as np

In [5]:
ipl=pd.read_csv("matches.csv")
nov=pd.read_csv("reg-month1.csv")
dec=pd.read_csv("reg-month2.csv")
courses=pd.read_csv("courses.csv")
students=pd.read_csv("students.csv")

In [62]:
#vertically stack or concatinate two similar dataframe
regs=pd.concat([nov,dec,],ignore_index=True)

In [63]:
#vertically stack two dataframe using append method
nov.append(dec)

<ipython-input-63-afd922421adf>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  nov.append(dec)

    student_id  course_id
0           23          1
1           15          5
2           18          6
3           23          4
4           16          9
5           18          1
6            1          1
7            7          8
8           22          3
9           15          1
10          19          4
11           1          6
12           7         10
13          11          7
14          13          3
15          24          4
16          21          1
17          16          5
18          23          3
19          17          7
20          23          6
21          25          1
22          19          2
23          25         10
24           3          3
0            3          5
1           16          7
2           12         10
3           12          1
4           14          9
5            7          7
6            7          2
7           16          3
8           17         10
9           11          8
10          14          6
11          12          5
12          12          7
13          18          8
14           1         10
15           1          9
16           2          5
17           7          6
18          22          5
19          22          6
20          23          9
21          23          5
22          14          4
23          14          1
24          11         10
25          42          9
26          50          8
27          38          1

In [64]:
#multi index dataframme
mul=pd.concat([nov,dec],keys=["nov","dec"])
mul

        student_id  course_id
nov 0           23          1
    1           15          5
    2           18          6
    3           23          4
    4           16          9
    5           18          1
    6            1          1
    7            7          8
    8           22          3
    9           15          1
    10          19          4
    11           1          6
    12           7         10
    13          11          7
    14          13          3
    15          24          4
    16          21          1
    17          16          5
    18          23          3
    19          17          7
    20          23          6
    21          25          1
    22          19          2
    23          25         10
    24           3          3
dec 0            3          5
    1           16          7
    2           12         10
    3           12          1
    4           14          9
    5            7          7
    6            7          2
    7           16          3
    8           17         10
    9           11          8
    10          14          6
    11          12          5
    12          12          7
    13          18          8
    14           1         10
    15           1          9
    16           2          5
    17           7          6
    18          22          5
    19          22          6
    20          23          9
    21          23          5
    22          14          4
    23          14          1
    24          11         10
    25          42          9
    26          50          8
    27          38          1

In [65]:
mul.loc[("dec",4)]

student_id    14
course_id      9
Name: (dec, 4), dtype: int64

In [66]:
mul.loc[("nov")]

    student_id  course_id
0           23          1
1           15          5
2           18          6
3           23          4
4           16          9
5           18          1
6            1          1
7            7          8
8           22          3
9           15          1
10          19          4
11           1          6
12           7         10
13          11          7
14          13          3
15          24          4
16          21          1
17          16          5
18          23          3
19          17          7
20          23          6
21          25          1
22          19          2
23          25         10
24           3          3

In [67]:
pd.concat([nov,dec],axis=1)
#virtically stack these both dataframe but index are same

    student_id  course_id  student_id  course_id
0         23.0        1.0           3          5
1         15.0        5.0          16          7
2         18.0        6.0          12         10
3         23.0        4.0          12          1
4         16.0        9.0          14          9
5         18.0        1.0           7          7
6          1.0        1.0           7          2
7          7.0        8.0          16          3
8         22.0        3.0          17         10
9         15.0        1.0          11          8
10        19.0        4.0          14          6
11         1.0        6.0          12          5
12         7.0       10.0          12          7
13        11.0        7.0          18          8
14        13.0        3.0           1         10
15        24.0        4.0           1          9
16        21.0        1.0           2          5
17        16.0        5.0           7          6
18        23.0        3.0          22          5
19        17.0        7.0          22          6
20        23.0        6.0          23          9
21        25.0        1.0          23          5
22        19.0        2.0          14          4
23        25.0       10.0          14          1
24         3.0        3.0          11         10
25         NaN        NaN          42          9
26         NaN        NaN          50          8
27         NaN        NaN          38          1

In [69]:
pd.concat([ipl,delevery],axis=1)

NameError: name 'delevery' is not defined

In [68]:
#inner join
#here students is left table, nov is right table, how means which type of join, on means on the basis of(a common column)
students.merge(nov,how="inner",on="student_id")

    student_id                name  partner  course_id
0            1       Kailash Harjo       23          1
1            1       Kailash Harjo       23          6
2            3      Parveen Bhalla        3          3
3            7        Tarun Thaker        9          8
4            7        Tarun Thaker        9         10
5           11  David Mukhopadhyay       20          7
6           13      Munni Varghese       24          3
7           15           Preet Sha       16          5
8           15           Preet Sha       16          1
9           16        Elias Dodiya       25          9
10          16        Elias Dodiya       25          5
11          17        Yasmin Palan        7          7
12          18     Fardeen Mahabir       13          6
13          18     Fardeen Mahabir       13          1
14          19        Qabeel Raman       12          4
15          19        Qabeel Raman       12          2
16          21          Seema Kota       15          1
17          22          Yash Sethi       21          3
18          23      Chhavi Lachman       18          1
19          23      Chhavi Lachman       18          4
20          23      Chhavi Lachman       18          3
21          23      Chhavi Lachman       18          6
22          24        Radhika Suri       17          4
23          25     Shashank D’Alia        2          1
24          25     Shashank D’Alia        2         10

In [70]:
#left join---> all value which is in the common and left table but not in right table
courses.merge(regs,how="left",on="course_id")

    course_id       course_name  price  student_id
0           1            python   2499        23.0
1           1            python   2499        18.0
2           1            python   2499         1.0
3           1            python   2499        15.0
4           1            python   2499        21.0
5           1            python   2499        25.0
6           1            python   2499        12.0
7           1            python   2499        14.0
8           1            python   2499        38.0
9           2               sql   3499        19.0
10          2               sql   3499         7.0
11          3     data analysis   4999        22.0
12          3     data analysis   4999        13.0
13          3     data analysis   4999        23.0
14          3     data analysis   4999         3.0
15          3     data analysis   4999        16.0
16          4  machine learning   9999        23.0
17          4  machine learning   9999        19.0
18          4  machine learning   9999        24.0
19          4  machine learning   9999        14.0
20          5           tableau   2499        15.0
21          5           tableau   2499        16.0
22          5           tableau   2499         3.0
23          5           tableau   2499        12.0
24          5           tableau   2499         2.0
25          5           tableau   2499        22.0
26          5           tableau   2499        23.0
27          6          power bi   1899        18.0
28          6          power bi   1899         1.0
29          6          power bi   1899        23.0
30          6          power bi   1899        14.0
31          6          power bi   1899         7.0
32          6          power bi   1899        22.0
33          7          ms sxcel   1599        11.0
34          7          ms sxcel   1599        17.0
35          7          ms sxcel   1599        16.0
36          7          ms sxcel   1599         7.0
37          7          ms sxcel   1599        12.0
38          8            pandas   1099         7.0
39          8            pandas   1099        11.0
40          8            pandas   1099        18.0
41          8            pandas   1099        50.0
42          9            plotly    699        16.0
43          9            plotly    699        14.0
44          9            plotly    699         1.0
45          9            plotly    699        23.0
46          9            plotly    699        42.0
47         10           pyspark   2499         7.0
48         10           pyspark   2499        25.0
49         10           pyspark   2499        12.0
50         10           pyspark   2499        17.0
51         10           pyspark   2499         1.0
52         10           pyspark   2499        11.0
53         11             Numpy    699         NaN
54         12               C++   1299         NaN

In [71]:
#right join---> which is exist in right table but not in left
students.merge(regs,how="right",on="student_id")

    student_id                name  partner  course_id
0           23      Chhavi Lachman     18.0          1
1           15           Preet Sha     16.0          5
2           18     Fardeen Mahabir     13.0          6
3           23      Chhavi Lachman     18.0          4
4           16        Elias Dodiya     25.0          9
5           18     Fardeen Mahabir     13.0          1
6            1       Kailash Harjo     23.0          1
7            7        Tarun Thaker      9.0          8
8           22          Yash Sethi     21.0          3
9           15           Preet Sha     16.0          1
10          19        Qabeel Raman     12.0          4
11           1       Kailash Harjo     23.0          6
12           7        Tarun Thaker      9.0         10
13          11  David Mukhopadhyay     20.0          7
14          13      Munni Varghese     24.0          3
15          24        Radhika Suri     17.0          4
16          21          Seema Kota     15.0          1
17          16        Elias Dodiya     25.0          5
18          23      Chhavi Lachman     18.0          3
19          17        Yasmin Palan      7.0          7
20          23      Chhavi Lachman     18.0          6
21          25     Shashank D’Alia      2.0          1
22          19        Qabeel Raman     12.0          2
23          25     Shashank D’Alia      2.0         10
24           3      Parveen Bhalla      3.0          3
25           3      Parveen Bhalla      3.0          5
26          16        Elias Dodiya     25.0          7
27          12          Radha Dutt     19.0         10
28          12          Radha Dutt     19.0          1
29          14    Pranab Natarajan     22.0          9
30           7        Tarun Thaker      9.0          7
31           7        Tarun Thaker      9.0          2
32          16        Elias Dodiya     25.0          3
33          17        Yasmin Palan      7.0         10
34          11  David Mukhopadhyay     20.0          8
35          14    Pranab Natarajan     22.0          6
36          12          Radha Dutt     19.0          5
37          12          Radha Dutt     19.0          7
38          18     Fardeen Mahabir     13.0          8
39           1       Kailash Harjo     23.0         10
40           1       Kailash Harjo     23.0          9
41           2         Esha Butala      1.0          5
42           7        Tarun Thaker      9.0          6
43          22          Yash Sethi     21.0          5
44          22          Yash Sethi     21.0          6
45          23      Chhavi Lachman     18.0          9
46          23      Chhavi Lachman     18.0          5
47          14    Pranab Natarajan     22.0          4
48          14    Pranab Natarajan     22.0          1
49          11  David Mukhopadhyay     20.0         10
50          42                 NaN      NaN          9
51          50                 NaN      NaN          8
52          38                 NaN      NaN          1

In [72]:
#full outer join--->common or own presonal data both are seen
students.merge(regs,how="outer",on="student_id")

    student_id                name  partner  course_id
0            1       Kailash Harjo     23.0        1.0
1            1       Kailash Harjo     23.0        6.0
2            1       Kailash Harjo     23.0       10.0
3            1       Kailash Harjo     23.0        9.0
4            2         Esha Butala      1.0        5.0
5            3      Parveen Bhalla      3.0        3.0
6            3      Parveen Bhalla      3.0        5.0
7            4         Marlo Dugal     14.0        NaN
8            5         Kusum Bahri      6.0        NaN
9            6  Lakshmi Contractor     10.0        NaN
10           7        Tarun Thaker      9.0        8.0
11           7        Tarun Thaker      9.0       10.0
12           7        Tarun Thaker      9.0        7.0
13           7        Tarun Thaker      9.0        2.0
14           7        Tarun Thaker      9.0        6.0
15           8      Radheshyam Dey      5.0        NaN
16           9   Nitika Chatterjee      4.0        NaN
17          10      Aayushman Sant      8.0        NaN
18          11  David Mukhopadhyay     20.0        7.0
19          11  David Mukhopadhyay     20.0        8.0
20          11  David Mukhopadhyay     20.0       10.0
21          12          Radha Dutt     19.0       10.0
22          12          Radha Dutt     19.0        1.0
23          12          Radha Dutt     19.0        5.0
24          12          Radha Dutt     19.0        7.0
25          13      Munni Varghese     24.0        3.0
26          14    Pranab Natarajan     22.0        9.0
27          14    Pranab Natarajan     22.0        6.0
28          14    Pranab Natarajan     22.0        4.0
29          14    Pranab Natarajan     22.0        1.0
30          15           Preet Sha     16.0        5.0
31          15           Preet Sha     16.0        1.0
32          16        Elias Dodiya     25.0        9.0
33          16        Elias Dodiya     25.0        5.0
34          16        Elias Dodiya     25.0        7.0
35          16        Elias Dodiya     25.0        3.0
36          17        Yasmin Palan      7.0        7.0
37          17        Yasmin Palan      7.0       10.0
38          18     Fardeen Mahabir     13.0        6.0
39          18     Fardeen Mahabir     13.0        1.0
40          18     Fardeen Mahabir     13.0        8.0
41          19        Qabeel Raman     12.0        4.0
42          19        Qabeel Raman     12.0        2.0
43          20       Hanuman Hegde     11.0        NaN
44          21          Seema Kota     15.0        1.0
45          22          Yash Sethi     21.0        3.0
46          22          Yash Sethi     21.0        5.0
47          22          Yash Sethi     21.0        6.0
48          23      Chhavi Lachman     18.0        1.0
49          23      Chhavi Lachman     18.0        4.0
50          23      Chhavi Lachman     18.0        3.0
51          23      Chhavi Lachman     18.0        6.0
52          23      Chhavi Lachman     18.0        9.0
53          23      Chhavi Lachman     18.0        5.0
54          24        Radhika Suri     17.0        4.0
55          25     Shashank D’Alia      2.0        1.0
56          25     Shashank D’Alia      2.0       10.0
57          42                 NaN      NaN        9.0
58          50                 NaN      NaN        8.0
59          38                 NaN      NaN        1.0

***prectice question***

In [9]:
# 1. find total revenue generated
total=regs.merge(courses,how="inner",on="course_id")["price"].sum()
total

154247

In [25]:
# 2.  find month by month revenue
tempdf=pd.concat([nov,dec],keys=["nov","dec"]).reset_index()
ans=tempdf.merge(courses,on="course_id").groupby("level_0").sum()
ans

<ipython-input-25-a562ab65ab44>:3: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  ans=tempdf.merge(courses,on="course_id").groupby("level_0").sum()

         level_1  student_id  course_id  price
level_0
dec          378         441        176  65072
nov          300         405        111  89175

In [31]:
# 3.  print the registration table--> cols--name,course,price
ans=regs.merge(students,on="student_id").merge(courses,on="course_id")
ans[["name","course_name","price"]]

                  name       course_name  price
0       Chhavi Lachman            python   2499
1            Preet Sha            python   2499
2      Fardeen Mahabir            python   2499
3        Kailash Harjo            python   2499
4           Seema Kota            python   2499
5      Shashank D’Alia            python   2499
6           Radha Dutt            python   2499
7     Pranab Natarajan            python   2499
8       Chhavi Lachman  machine learning   9999
9         Qabeel Raman  machine learning   9999
10        Radhika Suri  machine learning   9999
11    Pranab Natarajan  machine learning   9999
12      Chhavi Lachman     data analysis   4999
13        Elias Dodiya     data analysis   4999
14          Yash Sethi     data analysis   4999
15      Munni Varghese     data analysis   4999
16      Parveen Bhalla     data analysis   4999
17      Chhavi Lachman          power bi   1899
18     Fardeen Mahabir          power bi   1899
19       Kailash Harjo          power bi   1899
20        Tarun Thaker          power bi   1899
21          Yash Sethi          power bi   1899
22    Pranab Natarajan          power bi   1899
23      Chhavi Lachman            plotly    699
24        Elias Dodiya            plotly    699
25       Kailash Harjo            plotly    699
26    Pranab Natarajan            plotly    699
27      Chhavi Lachman           tableau   2499
28           Preet Sha           tableau   2499
29        Elias Dodiya           tableau   2499
30          Yash Sethi           tableau   2499
31      Parveen Bhalla           tableau   2499
32          Radha Dutt           tableau   2499
33         Esha Butala           tableau   2499
34     Fardeen Mahabir            pandas   1099
35        Tarun Thaker            pandas   1099
36  David Mukhopadhyay            pandas   1099
37        Elias Dodiya          ms sxcel   1599
38        Tarun Thaker          ms sxcel   1599
39  David Mukhopadhyay          ms sxcel   1599
40        Yasmin Palan          ms sxcel   1599
41          Radha Dutt          ms sxcel   1599
42       Kailash Harjo           pyspark   2499
43        Tarun Thaker           pyspark   2499
44  David Mukhopadhyay           pyspark   2499
45        Yasmin Palan           pyspark   2499
46     Shashank D’Alia           pyspark   2499
47          Radha Dutt           pyspark   2499
48        Tarun Thaker               sql   3499
49        Qabeel Raman               sql   3499

In [40]:
# 4.  find student who enroll both the month
stid=np.intersect1d(nov["student_id"],dec["student_id"])
students[students["student_id"].isin(stid)]

    student_id                name  partner
0            1       Kailash Harjo       23
2            3      Parveen Bhalla        3
6            7        Tarun Thaker        9
10          11  David Mukhopadhyay       20
15          16        Elias Dodiya       25
16          17        Yasmin Palan        7
17          18     Fardeen Mahabir       13
21          22          Yash Sethi       21
22          23      Chhavi Lachman       18

In [47]:
# 5.  find courses that get no enrollment
tempid=np.setdiff1d(courses["course_id"],regs["course_id"])
courses[courses["course_id"].isin(tempid)]

    course_id course_name  price
10         11       Numpy    699
11         12         C++   1299

In [58]:
# 6.  print student name ,partinar name for all enrolled student
both=students.merge(students,how="inner",left_on="partner",right_on="student_id")
both[["name_x","name_y"]]

                name_x              name_y
0        Kailash Harjo      Chhavi Lachman
1          Esha Butala       Kailash Harjo
2       Parveen Bhalla      Parveen Bhalla
3          Marlo Dugal    Pranab Natarajan
4          Kusum Bahri  Lakshmi Contractor
5   Lakshmi Contractor      Aayushman Sant
6         Tarun Thaker   Nitika Chatterjee
7       Radheshyam Dey         Kusum Bahri
8    Nitika Chatterjee         Marlo Dugal
9       Aayushman Sant      Radheshyam Dey
10  David Mukhopadhyay       Hanuman Hegde
11          Radha Dutt        Qabeel Raman
12      Munni Varghese        Radhika Suri
13    Pranab Natarajan          Yash Sethi
14           Preet Sha        Elias Dodiya
15        Elias Dodiya     Shashank D’Alia
16        Yasmin Palan        Tarun Thaker
17     Fardeen Mahabir      Munni Varghese
18        Qabeel Raman          Radha Dutt
19       Hanuman Hegde  David Mukhopadhyay
20          Seema Kota           Preet Sha
21          Yash Sethi          Seema Kota
22      Chhavi Lachman     Fardeen Mahabir
23        Radhika Suri        Yasmin Palan
24     Shashank D’Alia         Esha Butala